import alluraUrl from '@fontsource/allura/files/allura-latin-400-normal.woff?url'
import {
  Document,
  Font,
  Page,
  StyleSheet,
  Text,
  View,
} from '@react-pdf/renderer'
import type { Contact, Production, TrackingEntry } from '@/lib/db'
import type { PaperSize } from '@/lib/settings'

Font.register({ family: 'Allura', src: alluraUrl })

const SCENE_GRAY = '#d6d3d1'
const CREW_YELLOW = '#fef08a'

function pickTitleSize(name: string): number {
  const n = name.length
  if (n > 28) return 26
  if (n > 22) return 30
  if (n > 16) return 34
  return 38
}

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Times-Roman',
    fontSize: 9,
    paddingHorizontal: 36,
    paddingVertical: 48,
    lineHeight: 1.3,
  },
  title: {
    fontFamily: 'Allura',
    textAlign: 'center',
    marginBottom: 14,
    lineHeight: 1.3,
  },
  subtitle: {
    textAlign: 'center',
    fontSize: 11,
    marginBottom: 12,
    color: '#555',
  },
  tableHead: {
    flexDirection: 'row',
    backgroundColor: '#e7e5e4',
    fontFamily: 'Times-Bold',
    fontSize: 8,
    paddingVertical: 4,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#000',
  },
  row: {
    flexDirection: 'row',
    paddingVertical: 4,
    paddingHorizontal: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: '#e7e5e4',
  },
  sceneShiftRow: {
    backgroundColor: SCENE_GRAY,
    paddingVertical: 4,
    paddingHorizontal: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: '#a8a29e',
    textAlign: 'center',
    fontFamily: 'Times-Bold',
    fontSize: 9,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  crewRow: {
    flexDirection: 'row',
    paddingVertical: 4,
    paddingHorizontal: 4,
    backgroundColor: CREW_YELLOW,
    borderBottomWidth: 0.5,
    borderBottomColor: '#eab308',
  },
  cellPage: { width: '8%' },
  cellWho: { width: '28%', fontFamily: 'Times-Bold' },
  cellWhat: { width: '14%' },
  cellWhere: { width: '12%' },
  cellNotes: { width: '38%' },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 36,
    right: 36,
    fontSize: 7,
    color: '#888',
    textAlign: 'center',
  },
  pageNumber: {
    position: 'absolute',
    bottom: 12,
    right: 36,
    fontSize: 7,
    color: '#888',
  },
})

function abbreviateName(name: string): string {
  const parts = name.trim().split(/\s+/)
  if (parts.length < 2) return name
  return `${parts[0]![0]}. ${parts[parts.length - 1]}`
}

interface Props {
  production: Production
  entries: TrackingEntry[]
  contacts: Contact[]
  paperSize?: PaperSize
}

export default function TrackingPdf({
  production,
  entries,
  contacts,
  paperSize = 'LETTER',
}: Props) {
  const nameOf = (id: number): string =>
    contacts.find((c) => c.id === id)?.name ?? '(removed)'

  const renderWho = (entry: TrackingEntry): string => {
    if (entry.whoOverride && entry.contactIds.length === 0) {
      return entry.whoOverride
    }
    const names = entry.contactIds.map((id) => abbreviateName(nameOf(id)))
    if (entry.whoOverride) names.push(entry.whoOverride)
    return names.join(', ')
  }

  const titleSize = pickTitleSize(production.name)

  return (
    <Document
      title={`${production.name} — Master Tracking`}
      author="Standby"
    >
      <Page size={paperSize} style={styles.page}>
        <Text style={[styles.title, { fontSize: titleSize }]}>
          {production.name}
        </Text>
        <Text style={styles.subtitle}>Master Tracking Sheet</Text>

        <View style={styles.tableHead} fixed>
          <Text style={styles.cellPage}>PAGE</Text>
          <Text style={styles.cellWho}>WHO</Text>
          <Text style={styles.cellWhat}>WHAT</Text>
          <Text style={styles.cellWhere}>WHERE</Text>
          <Text style={styles.cellNotes}>NOTES</Text>
        </View>

        {entries.map((e, i) => {
          if (e.kind === 'scene-shift') {
            return (
              <Text key={i} style={styles.sceneShiftRow}>
                {e.sceneLabel || 'SCENE SHIFT'}
              </Text>
            )
          }
          const isCrew = e.kind === 'crew'
          const rowStyle = isCrew ? styles.crewRow : styles.row
          return (
            <View key={i} style={rowStyle} wrap={false}>
              <Text style={styles.cellPage}>{e.page}</Text>
              <Text style={styles.cellWho}>{renderWho(e)}</Text>
              <Text style={styles.cellWhat}>{e.what}</Text>
              <Text style={styles.cellWhere}>{e.where}</Text>
              <Text style={styles.cellNotes}>{e.notes ?? ''}</Text>
            </View>
          )
        })}

        <Text style={styles.footer} fixed>
          {production.name} · Master Tracking · Generated by Standby
        </Text>
        <Text
          style={styles.pageNumber}
          render={({ pageNumber, totalPages }) =>
            `${pageNumber} / ${totalPages}`
          }
          fixed
        />
      </Page>
    </Document>
  )
}
