import { Button, Field, Input } from '@/components/Form'
import { useAppStore } from '@/lib/store'
import {
  FONT_SIZE_DESCRIPTIONS,
  FONT_SIZE_LABELS,
  PAPER_SIZE_LABELS,
  THEMES,
  THEME_ORDER,
  TIME_FORMAT_LABELS,
  type FontSize,
  type PaperSize,
  type Theme,
  type TimeFormat,
} from '@/lib/settings'

const FONT_SIZES: FontSize[] = ['sm', 'md', 'lg', 'xl']
const PAPER_SIZES: PaperSize[] = ['LETTER', 'A4']
const TIME_FORMATS: TimeFormat[] = ['12h', '24h']

export default function Settings() {
  const settings = useAppStore((s) => s.settings)
  const updateSettings = useAppStore((s) => s.updateSettings)
  const resetSettings = useAppStore((s) => s.resetSettings)

  return (
    <section className="mx-auto max-w-4xl space-y-12">
      <header>
        <h2 className="text-3xl font-semibold">Settings</h2>
        <p className="mt-1 text-sm text-muted">
          Personal preferences. Stored in your browser; never leave this device.
        </p>
      </header>

      {/* Your name */}
      <section className="space-y-3">
        <div>
          <h3 className="text-xl font-semibold">Your name</h3>
          <p className="text-sm text-muted">
            Used to greet you on the dashboard and to sign off the email
            bodies generated by the Distribute panels (so recipients see
            "— {settings.userName || 'Rayne'}" at the bottom of the report
            and know who sent it). Leave blank to skip personalization
            everywhere.
          </p>
        </div>
        <Field label="Name (or how you sign off)">
          <Input
            value={settings.userName ?? ''}
            onChange={(e) => updateSettings({ userName: e.target.value })}
            placeholder="e.g. Rayne"
            className="max-w-sm"
          />
        </Field>
      </section>

      {/* Theme */}
      <section className="space-y-4">
        <div>
          <h3 className="text-xl font-semibold">Theme</h3>
          <p className="text-sm text-muted">
            Each theme changes the fonts, surface colors, accent, and border
            radius — try a few. Light / dark mode toggle stays in the left
            nav and works with every theme.
          </p>
        </div>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {THEME_ORDER.map((theme) => (
            <ThemeCard
              key={theme}
              theme={theme}
              selected={settings.theme === theme}
              onSelect={() => updateSettings({ theme })}
            />
          ))}
        </div>
      </section>

      {/* Font size */}
      <section className="space-y-3">
        <div>
          <h3 className="text-xl font-semibold">Font size</h3>
          <p className="text-sm text-muted">
            Scales the entire UI. Bump it up for reading from across a booth.
          </p>
        </div>
        <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
          {FONT_SIZES.map((size) => (
            <button
              key={size}
              type="button"
              onClick={() => updateSettings({ fontSize: size })}
              className={`flex flex-col items-start gap-1 rounded-theme border p-3 text-left transition ${
                settings.fontSize === size
                  ? 'border-accent bg-accent/5 ring-1 ring-accent'
                  : 'border-surface-border hover:border-accent'
              }`}
            >
              <span className="font-medium">{FONT_SIZE_LABELS[size]}</span>
              <span className="text-xs text-muted">
                {FONT_SIZE_DESCRIPTIONS[size]}
              </span>
            </button>
          ))}
        </div>
      </section>

      {/* Time format */}
      <section className="space-y-3">
        <div>
          <h3 className="text-xl font-semibold">Time format</h3>
          <p className="text-sm text-muted">
            How call times and rehearsal start/end times are displayed in
            the UI and in generated PDFs.
          </p>
        </div>
        <div className="grid gap-2 sm:grid-cols-2">
          {TIME_FORMATS.map((fmt) => (
            <button
              key={fmt}
              type="button"
              onClick={() => updateSettings({ timeFormat: fmt })}
              className={`rounded-theme border p-3 text-left transition ${
                settings.timeFormat === fmt
                  ? 'border-accent bg-accent/5 ring-1 ring-accent'
                  : 'border-surface-border hover:border-accent'
              }`}
            >
              <span className="font-medium">{TIME_FORMAT_LABELS[fmt]}</span>
            </button>
          ))}
        </div>
      </section>

      {/* PDF paper size */}
      <section className="space-y-3">
        <div>
          <h3 className="text-xl font-semibold">PDF paper size</h3>
          <p className="text-sm text-muted">
            Applied to every PDF Standby generates.
          </p>
        </div>
        <div className="grid gap-2 sm:grid-cols-2">
          {PAPER_SIZES.map((size) => (
            <button
              key={size}
              type="button"
              onClick={() => updateSettings({ paperSize: size })}
              className={`rounded-theme border p-3 text-left transition ${
                settings.paperSize === size
                  ? 'border-accent bg-accent/5 ring-1 ring-accent'
                  : 'border-surface-border hover:border-accent'
              }`}
            >
              <span className="font-medium">{PAPER_SIZE_LABELS[size]}</span>
            </button>
          ))}
        </div>
      </section>

      <section className="border-t border-surface-border pt-6">
        <Button variant="ghost" onClick={resetSettings}>
          Reset all to default
        </Button>
      </section>
    </section>
  )
}

interface ThemeCardProps {
  theme: Theme
  selected: boolean
  onSelect: () => void
}

/**
 * Each theme card has `data-theme={theme}` on the button itself, so all of
 * the CSS variables inside (--accent, --surface-elev, --font-display, etc.)
 * resolve to THAT theme's values regardless of which theme is currently
 * active on <html>. The card is a real preview, not a tinted swatch.
 */
function ThemeCard({ theme, selected, onSelect }: ThemeCardProps) {
  const meta = THEMES[theme]
  return (
    <button
      type="button"
      onClick={onSelect}
      data-theme={theme}
      className={`group flex flex-col items-stretch gap-3 rounded-theme border bg-card p-4 text-left transition ${
        selected
          ? 'border-accent ring-2 ring-accent'
          : 'border-surface-border hover:border-accent'
      }`}
    >
      {/* Typography preview — h4 picks up theme font + tracking + transform
          from the global @layer base rule. */}
      <div className="flex items-end justify-between gap-3">
        <h4 className="m-0 text-5xl leading-none">Aa</h4>
        <div className="text-right text-xs text-muted">
          <div>{meta.displayFont}</div>
          {meta.bodyFont !== meta.displayFont && (
            <div className="opacity-75">+ {meta.bodyFont}</div>
          )}
        </div>
      </div>

      {/* Accent pill — uses the theme's accent + on-accent + tracking */}
      <h4 className="m-0 inline-block self-start rounded-theme bg-accent px-3 py-1 text-xs leading-tight text-on-accent">
        {meta.tagline}
      </h4>

      {/* Theme name in its body font */}
      <div>
        <p className="text-lg font-semibold">{meta.label}</p>
        <p className="text-xs text-muted">{meta.description}</p>
      </div>

      {selected && (
        <span className="text-xs font-medium text-accent">✓ Selected</span>
      )}
    </button>
  )
}
