import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
} from '@react-pdf/renderer'
import type { Contact, Production } from '@/lib/db'
import type { PaperSize } from '@/lib/settings'

// Letter paper, formal serif (Times-Roman). Excludes contacts flagged
// doNotPublish. Private fields (emergency contact, medical) are NEVER
// included — see Field hints in ContactForm.

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Times-Roman',
    fontSize: 10,
    paddingHorizontal: 54,
    paddingVertical: 54,
    lineHeight: 1.35,
  },
  title: {
    fontFamily: 'Times-Bold',
    fontSize: 18,
    marginBottom: 2,
  },
  subtitle: {
    fontSize: 10,
    color: '#555',
    marginBottom: 18,
  },
  sectionHeader: {
    fontFamily: 'Times-Bold',
    fontSize: 12,
    marginTop: 14,
    marginBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#000',
    paddingBottom: 2,
  },
  tableHead: {
    flexDirection: 'row',
    fontFamily: 'Times-Bold',
    fontSize: 9,
    color: '#555',
    paddingVertical: 3,
    borderBottomWidth: 0.5,
    borderBottomColor: '#999',
  },
  row: {
    flexDirection: 'row',
    paddingVertical: 3,
    borderBottomWidth: 0.5,
    borderBottomColor: '#e5e5e5',
  },
  nameCell: { width: '28%' },
  nameCellBold: { width: '28%', fontFamily: 'Times-Bold' },
  roleCell: { width: '22%' },
  emailCell: { width: '24%' },
  phoneCell: { width: '14%' },
  pronounsCell: { width: '12%' },
  footer: {
    position: 'absolute',
    bottom: 36,
    left: 54,
    right: 54,
    fontSize: 8,
    color: '#888',
    textAlign: 'center',
    borderTopWidth: 0.5,
    borderTopColor: '#bbb',
    paddingTop: 6,
  },
  pageNumber: {
    position: 'absolute',
    bottom: 24,
    right: 54,
    fontSize: 8,
    color: '#888',
  },
})

const CATEGORY_LABELS: Record<Contact['category'], string> = {
  cast: 'Cast',
  creative: 'Creative Team',
  production: 'Production Team',
  crew: 'Crew',
  'venue-admin': 'Venue & Administration',
}

const CATEGORY_ORDER: Contact['category'][] = [
  'cast',
  'creative',
  'production',
  'crew',
  'venue-admin',
]

interface Props {
  production: Production
  contacts: Contact[]
  paperSize?: PaperSize
}

export default function ContactSheetPdf({
  production,
  contacts,
  paperSize = 'LETTER',
}: Props) {
  const publishable = contacts.filter((c) => !c.doNotPublish)
  const byCategory: Record<Contact['category'], Contact[]> = {
    cast: [],
    creative: [],
    production: [],
    crew: [],
    'venue-admin': [],
  }
  for (const c of publishable) byCategory[c.category].push(c)

  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  return (
    <Document
      title={`${production.name} — Contact Sheet`}
      author="Standby"
    >
      <Page size={paperSize} style={styles.page}>
        <Text style={styles.title}>{production.name}</Text>
        <Text style={styles.subtitle}>
          Contact Sheet · {today}
        </Text>

        {CATEGORY_ORDER.map((cat) => {
          const list = byCategory[cat]
          if (list.length === 0) return null
          return (
            <View key={cat} wrap={false}>
              <Text style={styles.sectionHeader}>
                {CATEGORY_LABELS[cat]}
              </Text>
              <View style={styles.tableHead}>
                <Text style={styles.nameCell}>Name</Text>
                <Text style={styles.roleCell}>Role</Text>
                <Text style={styles.emailCell}>Email</Text>
                <Text style={styles.phoneCell}>Phone</Text>
                <Text style={styles.pronounsCell}>Pronouns</Text>
              </View>
              {list.map((c, i) => (
                <View key={i} style={styles.row}>
                  <Text style={styles.nameCellBold}>{c.name}</Text>
                  <Text style={styles.roleCell}>{c.role ?? ''}</Text>
                  <Text style={styles.emailCell}>{c.email ?? ''}</Text>
                  <Text style={styles.phoneCell}>{c.phone ?? ''}</Text>
                  <Text style={styles.pronounsCell}>{c.pronouns ?? ''}</Text>
                </View>
              ))}
            </View>
          )
        })}

        <Text style={styles.footer} fixed>
          {production.name} · Contact Sheet · Generated by Standby
        </Text>
        <Text
          style={styles.pageNumber}
          render={({ pageNumber, totalPages }) =>
            `${pageNumber} / ${totalPages}`
          }
          fixed
        />
      </Page>
    </Document>
  )
}
