import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
} from '@react-pdf/renderer'
import type { Contact, LineNote, Production } from '@/lib/db'
import { LINE_TYPE_LABELS } from '@/lib/schemas'

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Times-Roman',
    fontSize: 10,
    paddingHorizontal: 54,
    paddingVertical: 54,
    lineHeight: 1.4,
  },
  title: {
    fontFamily: 'Times-Bold',
    fontSize: 16,
    marginBottom: 2,
  },
  subtitle: {
    fontSize: 10,
    color: '#555',
    marginBottom: 14,
  },
  actorName: {
    fontFamily: 'Times-Bold',
    fontSize: 14,
    marginBottom: 6,
  },
  introCopy: {
    fontSize: 9,
    color: '#555',
    marginBottom: 14,
    fontStyle: 'italic',
  },
  noteCard: {
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: '#ccc',
  },
  noteMeta: {
    fontSize: 9,
    color: '#666',
    marginBottom: 3,
  },
  noteRow: {
    flexDirection: 'row',
    marginBottom: 2,
  },
  noteLabel: {
    width: 70,
    fontFamily: 'Times-Bold',
    color: '#444',
  },
  noteText: {
    flex: 1,
  },
  noteComment: {
    fontSize: 9,
    color: '#666',
    marginTop: 3,
    fontStyle: 'italic',
  },
  footer: {
    position: 'absolute',
    bottom: 36,
    left: 54,
    right: 54,
    fontSize: 8,
    color: '#888',
    textAlign: 'center',
    borderTopWidth: 0.5,
    borderTopColor: '#bbb',
    paddingTop: 6,
  },
  pageNumber: {
    position: 'absolute',
    bottom: 24,
    right: 54,
    fontSize: 8,
    color: '#888',
  },
})

interface Props {
  production: Production
  actor: Contact
  notes: LineNote[]
}

/** Per-actor line notes PDF. Only contains that actor's notes. */
export default function LineNotesPdf({ production, actor, notes }: Props) {
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  return (
    <Document
      title={`${production.name} — Line notes for ${actor.name}`}
      author="Standby"
    >
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.title}>{production.name}</Text>
        <Text style={styles.subtitle}>Line notes · Issued {today}</Text>

        <Text style={styles.actorName}>{actor.name}</Text>
        <Text style={styles.introCopy}>
          Notes below capture moments where your delivery differed from the
          script. Take a quick look before our next rehearsal — questions on
          any of them, ask the SM or AD.
        </Text>

        {notes.length === 0 ? (
          <Text>No notes for this rehearsal cycle. Nice work.</Text>
        ) : (
          notes.map((n, i) => (
            <View key={i} style={styles.noteCard} wrap={false}>
              <Text style={styles.noteMeta}>
                {n.rehearsalDate}{' '}
                {n.page ? `· p.${n.page} ` : ''}·{' '}
                {LINE_TYPE_LABELS[n.lineType]}
              </Text>
              {n.scriptedText && (
                <View style={styles.noteRow}>
                  <Text style={styles.noteLabel}>Scripted:</Text>
                  <Text style={styles.noteText}>{n.scriptedText}</Text>
                </View>
              )}
              {n.spokenText && (
                <View style={styles.noteRow}>
                  <Text style={styles.noteLabel}>Spoken:</Text>
                  <Text style={styles.noteText}>{n.spokenText}</Text>
                </View>
              )}
              {n.comment && <Text style={styles.noteComment}>{n.comment}</Text>}
            </View>
          ))
        )}

        <Text style={styles.footer} fixed>
          {production.name} · Line notes for {actor.name} · Generated by Standby
        </Text>
        <Text
          style={styles.pageNumber}
          render={({ pageNumber, totalPages }) =>
            `${pageNumber} / ${totalPages}`
          }
          fixed
        />
      </Page>
    </Document>
  )
}
