import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
} from '@react-pdf/renderer'
import type { Production, Prop } from '@/lib/db'
import type { PaperSize } from '@/lib/settings'
import {
  PROP_SOURCE_LABELS,
  PROP_SPECIAL_HANDLING_LABELS,
  PROP_STATUS_LABELS,
} from '@/lib/schemas'

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Times-Roman',
    fontSize: 9,
    paddingHorizontal: 36,
    paddingVertical: 54,
    lineHeight: 1.3,
  },
  title: {
    fontFamily: 'Times-Bold',
    fontSize: 16,
    marginBottom: 2,
  },
  subtitle: {
    fontSize: 9,
    color: '#555',
    marginBottom: 14,
  },
  tableHead: {
    flexDirection: 'row',
    fontFamily: 'Times-Bold',
    fontSize: 8,
    color: '#555',
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#000',
  },
  row: {
    flexDirection: 'row',
    paddingVertical: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: '#ddd',
  },
  cellName: { width: '24%', paddingRight: 4 },
  cellScenes: { width: '14%', paddingRight: 4 },
  cellChars: { width: '18%', paddingRight: 4 },
  cellStatus: { width: '12%', paddingRight: 4 },
  cellSource: { width: '12%', paddingRight: 4 },
  cellTags: { width: '20%' },
  nameMain: { fontFamily: 'Times-Bold' },
  consumable: { fontSize: 7, color: '#888', fontStyle: 'italic' },
  notes: { fontSize: 7, color: '#666', marginTop: 1 },
  footer: {
    position: 'absolute',
    bottom: 36,
    left: 36,
    right: 36,
    fontSize: 7,
    color: '#888',
    textAlign: 'center',
    borderTopWidth: 0.5,
    borderTopColor: '#bbb',
    paddingTop: 6,
  },
  pageNumber: {
    position: 'absolute',
    bottom: 24,
    right: 36,
    fontSize: 7,
    color: '#888',
  },
})

interface Props {
  production: Production
  props: Prop[]
  paperSize?: PaperSize
}

export default function PropListPdf({
  production,
  props,
  paperSize = 'LETTER',
}: Props) {
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  return (
    <Document
      title={`${production.name} — Prop List`}
      author="Standby"
    >
      <Page size={paperSize} style={styles.page}>
        <Text style={styles.title}>{production.name}</Text>
        <Text style={styles.subtitle}>
          Prop List · {props.length} items · {today}
        </Text>

        <View style={styles.tableHead}>
          <Text style={styles.cellName}>Prop</Text>
          <Text style={styles.cellScenes}>Scenes</Text>
          <Text style={styles.cellChars}>Characters</Text>
          <Text style={styles.cellStatus}>Status</Text>
          <Text style={styles.cellSource}>Source</Text>
          <Text style={styles.cellTags}>Handling</Text>
        </View>
        {props.map((p, i) => (
          <View key={i} style={styles.row} wrap={false}>
            <View style={styles.cellName}>
              <Text style={styles.nameMain}>{p.name}</Text>
              {p.consumable && (
                <Text style={styles.consumable}>consumable</Text>
              )}
              {p.notes && <Text style={styles.notes}>{p.notes}</Text>}
            </View>
            <Text style={styles.cellScenes}>
              {p.scenes.length > 0 ? p.scenes.join(', ') : '—'}
            </Text>
            <Text style={styles.cellChars}>
              {p.characters.length > 0 ? p.characters.join(', ') : '—'}
            </Text>
            <Text style={styles.cellStatus}>
              {PROP_STATUS_LABELS[p.status]}
            </Text>
            <Text style={styles.cellSource}>
              {PROP_SOURCE_LABELS[p.source]}
            </Text>
            <Text style={styles.cellTags}>
              {p.specialHandling && p.specialHandling.length > 0
                ? p.specialHandling
                    .map((t) => PROP_SPECIAL_HANDLING_LABELS[t])
                    .join(', ')
                : '—'}
            </Text>
          </View>
        ))}

        <Text style={styles.footer} fixed>
          {production.name} · Prop List · Generated by Standby
        </Text>
        <Text
          style={styles.pageNumber}
          render={({ pageNumber, totalPages }) =>
            `${pageNumber} / ${totalPages}`
          }
          fixed
        />
      </Page>
    </Document>
  )
}
