import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
} from '@react-pdf/renderer'
import type { Production } from '@/lib/db'

// Letter paper, 0.75-inch margins, Times-Roman body — formal Broadway-PSM
// packet aesthetic.

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Times-Roman',
    fontSize: 11,
    paddingHorizontal: 54,
    paddingVertical: 54,
    lineHeight: 1.4,
  },
  title: {
    fontFamily: 'Times-Bold',
    fontSize: 18,
    marginBottom: 2,
  },
  subtitle: {
    fontSize: 10,
    color: '#555',
    marginBottom: 18,
  },
  sectionHeader: {
    fontFamily: 'Times-Bold',
    fontSize: 12,
    marginTop: 16,
    marginBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#000',
    paddingBottom: 2,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 3,
  },
  label: {
    width: 130,
    fontFamily: 'Times-Bold',
  },
  value: {
    flex: 1,
  },
  footer: {
    position: 'absolute',
    bottom: 36,
    left: 54,
    right: 54,
    fontSize: 8,
    color: '#888',
    textAlign: 'center',
    borderTopWidth: 0.5,
    borderTopColor: '#bbb',
    paddingTop: 6,
  },
})

const TYPE_LABELS: Record<Production['type'], string> = {
  play: 'Play',
  musical: 'Musical',
  devised: 'Devised',
  cabaret: 'Cabaret',
  other: 'Other',
}

function formatDate(iso?: string): string {
  if (!iso) return '—'
  // iso is YYYY-MM-DD from the date input
  const [year, month, day] = iso.split('-').map(Number)
  if (!year || !month || !day) return iso
  const date = new Date(Date.UTC(year, month - 1, day))
  return date.toLocaleDateString('en-US', {
    weekday: 'short',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'UTC',
  })
}

function Row({ label, value }: { label: string; value?: string }) {
  return (
    <View style={styles.row}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{value && value.length > 0 ? value : '—'}</Text>
    </View>
  )
}

interface Props {
  production: Production
}

export default function ProductionInfoPdf({ production }: Props) {
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  return (
    <Document
      title={`${production.name} — Production Information`}
      author="Standby"
    >
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.title}>{production.name}</Text>
        <Text style={styles.subtitle}>
          Production Information Sheet · Generated {today}
        </Text>

        <Text style={styles.sectionHeader}>Production</Text>
        <Row label="Working title" value={production.workingTitle} />
        <Row label="Season" value={production.season} />
        <Row label="Type" value={TYPE_LABELS[production.type]} />
        <Row label="Organization" value={production.organization} />
        <Row label="Venue" value={production.venue} />

        <Text style={styles.sectionHeader}>Key Dates</Text>
        <Row label="First rehearsal" value={formatDate(production.firstRehearsal)} />
        <Row label="Designer run" value={formatDate(production.designerRun)} />
        <Row label="Tech start" value={formatDate(production.techStart)} />
        <Row label="First preview" value={formatDate(production.firstPreview)} />
        <Row label="Opening" value={formatDate(production.opening)} />
        <Row label="Closing" value={formatDate(production.closing)} />

        <Text style={styles.footer} fixed>
          {production.name} · Generated by Standby ·{' '}
          <Text>https://shannonh.github.io/standby/</Text>
        </Text>
      </Page>
    </Document>
  )
}
